-- ─────────────────────────────────────────────────────────────────────────────
-- Advantage Journal Portal — initial schema
--
-- Mirrors the TypeScript models in `lib/types.ts` and the Zod contracts in
-- `lib/contracts/index.ts`. Field naming uses snake_case in Postgres while
-- the application layer uses camelCase; the SupabaseAdapter is responsible
-- for translation in both directions.
--
-- Conventions:
--   - Primary keys are uuid generated by Postgres (`gen_random_uuid()`).
--   - Every table has `created_at`. Mutable tables also get `updated_at`,
--     maintained by the `tg_set_updated_at` trigger.
--   - Soft enums use Postgres enum types. Free-form text fields use
--     `text` rather than `varchar(n)` since Postgres has no perf delta.
--   - RLS is enabled on every table. Default policies are intentionally
--     permissive for authenticated users; tighten in a follow-up migration
--     once the production permission matrix is locked in.
-- ─────────────────────────────────────────────────────────────────────────────

create extension if not exists "pgcrypto";

-- ── enums ─────────────────────────────────────────────────────────────────
create type app_role as enum ('writer', 'editor', 'leader', 'admin');

create type task_status as enum (
  'not_started',
  'in_progress',
  'submitted',
  'complete'
);

create type task_color as enum ('green', 'amber', 'red');

create type review_decision as enum (
  'approved',
  'changes_requested',
  'rejected'
);

create type submission_type as enum ('file', 'google_doc', 'inline');

create type conversation_kind as enum (
  'dm',
  'group',
  'all_team',
  'issue',
  'admins_only'
);

create type notification_kind as enum (
  'task_assigned',
  'deadline',
  'submission',
  'comment',
  'review_decision',
  'task_complete',
  'message',
  'announcement'
);

create type extension_status as enum ('pending', 'approved', 'denied');

create type moderation_status as enum (
  'open',
  'in_review',
  'resolved',
  'dismissed'
);

create type moderation_severity as enum ('low', 'medium', 'high');

create type moderation_reason as enum (
  'inappropriate_language',
  'bullying_or_harassment',
  'personal_information',
  'off_topic_or_spam',
  'other'
);

-- ── shared updated_at trigger ─────────────────────────────────────────────
create or replace function public.tg_set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ── users / profiles ──────────────────────────────────────────────────────
-- The `users` table mirrors `auth.users`. A trigger inserts a row at signup
-- (see §7 in docs/supabase-setup-guide.md). For now `id` is plain uuid so
-- the seed file can pre-populate demo users without an auth dependency.
create table if not exists public.users (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  email       text not null unique,
  role        app_role not null default 'writer',
  avatar_url  text,
  active      boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists idx_users_role on public.users (role);
create index if not exists idx_users_active on public.users (active);

create trigger users_set_updated_at
  before update on public.users
  for each row execute function public.tg_set_updated_at();

-- ── tasks ─────────────────────────────────────────────────────────────────
create table if not exists public.tasks (
  id                       uuid primary key default gen_random_uuid(),
  title                    text not null,
  instructions             text not null default '',
  writer_id                uuid not null references public.users(id) on delete restrict,
  editor_id                uuid references public.users(id) on delete set null,
  deadline                 timestamptz not null,
  status                   task_status not null default 'not_started',
  color                    task_color not null default 'green',
  current_submission_id    uuid,
  word_count_target        integer check (word_count_target is null or word_count_target > 0),
  citations_required       boolean not null default false,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

create index if not exists idx_tasks_writer on public.tasks (writer_id);
create index if not exists idx_tasks_editor on public.tasks (editor_id);
create index if not exists idx_tasks_status on public.tasks (status);
create index if not exists idx_tasks_deadline on public.tasks (deadline);

create trigger tasks_set_updated_at
  before update on public.tasks
  for each row execute function public.tg_set_updated_at();

-- ── submissions ───────────────────────────────────────────────────────────
create table if not exists public.submissions (
  id              uuid primary key default gen_random_uuid(),
  task_id         uuid not null references public.tasks(id) on delete cascade,
  type            submission_type not null,
  version         integer not null check (version > 0),
  content         text not null,
  file_filename   text,
  file_mime_type  text,
  file_size_bytes bigint check (file_size_bytes is null or file_size_bytes >= 0),
  is_current      boolean not null default false,
  created_at      timestamptz not null default now(),
  unique (task_id, version)
);

create index if not exists idx_submissions_task on public.submissions (task_id);
create index if not exists idx_submissions_current
  on public.submissions (task_id) where is_current;

-- After creating submissions table we can FK current_submission_id back.
alter table public.tasks
  add constraint tasks_current_submission_fk
    foreign key (current_submission_id)
    references public.submissions(id)
    on delete set null
    deferrable initially deferred;

-- ── reviews ───────────────────────────────────────────────────────────────
create table if not exists public.reviews (
  id             uuid primary key default gen_random_uuid(),
  submission_id  uuid not null references public.submissions(id) on delete cascade,
  reviewer_id    uuid not null references public.users(id) on delete restrict,
  decision       review_decision not null,
  notes          text,
  created_at     timestamptz not null default now()
);

create index if not exists idx_reviews_submission on public.reviews (submission_id);
create index if not exists idx_reviews_reviewer on public.reviews (reviewer_id);

-- ── comments ──────────────────────────────────────────────────────────────
create table if not exists public.comments (
  id             uuid primary key default gen_random_uuid(),
  submission_id  uuid not null references public.submissions(id) on delete cascade,
  author_id      uuid not null references public.users(id) on delete restrict,
  body           text not null,
  inline         boolean not null default false,
  line_number    integer check (line_number is null or line_number > 0),
  resolved       boolean not null default false,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  -- inline comments must carry a line number
  constraint comments_inline_requires_line
    check ((inline = false) or (line_number is not null))
);

create index if not exists idx_comments_submission on public.comments (submission_id);
create index if not exists idx_comments_resolved on public.comments (resolved);

create trigger comments_set_updated_at
  before update on public.comments
  for each row execute function public.tg_set_updated_at();

-- ── conversations + members ──────────────────────────────────────────────
create table if not exists public.conversations (
  id              uuid primary key default gen_random_uuid(),
  kind            conversation_kind not null,
  title           text not null,
  last_message_at timestamptz,
  created_at      timestamptz not null default now()
);

create index if not exists idx_conversations_kind on public.conversations (kind);
create index if not exists idx_conversations_last_message
  on public.conversations (last_message_at desc nulls last);

create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id         uuid not null references public.users(id) on delete cascade,
  joined_at       timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

create index if not exists idx_conversation_members_user
  on public.conversation_members (user_id);

-- ── messages ──────────────────────────────────────────────────────────────
create table if not exists public.messages (
  id              uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  author_id       uuid not null references public.users(id) on delete restrict,
  body            text not null,
  pinned_at       timestamptz,
  hidden_at       timestamptz,
  created_at      timestamptz not null default now()
);

create index if not exists idx_messages_conversation_created
  on public.messages (conversation_id, created_at);
create index if not exists idx_messages_pinned
  on public.messages (conversation_id) where pinned_at is not null;

-- ── notifications ─────────────────────────────────────────────────────────
create table if not exists public.notifications (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.users(id) on delete cascade,
  kind        notification_kind not null,
  title       text not null,
  body        text,
  read        boolean not null default false,
  created_at  timestamptz not null default now()
);

create index if not exists idx_notifications_user_read_created
  on public.notifications (user_id, read, created_at desc);

-- ── extension_requests ────────────────────────────────────────────────────
create table if not exists public.extension_requests (
  id               uuid primary key default gen_random_uuid(),
  task_id          uuid not null references public.tasks(id) on delete cascade,
  requested_by_id  uuid not null references public.users(id) on delete restrict,
  new_deadline     timestamptz not null,
  reason           text not null,
  status           extension_status not null default 'pending',
  decided_by_id    uuid references public.users(id) on delete set null,
  decided_at       timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists idx_extension_requests_task
  on public.extension_requests (task_id);
create index if not exists idx_extension_requests_status
  on public.extension_requests (status);

create trigger extension_requests_set_updated_at
  before update on public.extension_requests
  for each row execute function public.tg_set_updated_at();

-- Only one pending extension per task at a time. Approved/denied requests
-- coexist as historical record.
create unique index if not exists ux_extension_requests_one_pending
  on public.extension_requests (task_id)
  where status = 'pending';

-- ── moderation_reports ────────────────────────────────────────────────────
create table if not exists public.moderation_reports (
  id                uuid primary key default gen_random_uuid(),
  message_id        uuid not null references public.messages(id) on delete cascade,
  conversation_id   uuid not null references public.conversations(id) on delete cascade,
  reported_user_id  uuid not null references public.users(id) on delete restrict,
  reporter_id       uuid not null references public.users(id) on delete restrict,
  reason            moderation_reason not null default 'other',
  reporter_note     text,
  status            moderation_status not null default 'open',
  severity          moderation_severity not null default 'medium',
  resolved_by_id    uuid references public.users(id) on delete set null,
  resolved_at       timestamptz,
  internal_note     text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  -- One report per (reporter, message) — duplicates are bumped instead.
  unique (message_id, reporter_id)
);

create index if not exists idx_moderation_reports_status
  on public.moderation_reports (status);
create index if not exists idx_moderation_reports_severity
  on public.moderation_reports (severity);
create index if not exists idx_moderation_reports_created
  on public.moderation_reports (created_at desc);
create index if not exists idx_moderation_reports_reported_user
  on public.moderation_reports (reported_user_id);

create trigger moderation_reports_set_updated_at
  before update on public.moderation_reports
  for each row execute function public.tg_set_updated_at();

-- ── audit_events ──────────────────────────────────────────────────────────
-- Append-only event log for admin oversight. Never updated; deletion only
-- by retention jobs. The current portal derives a mock log from the
-- notifications table on the Admin page; once this table is in place, the
-- Admin page can read from here for a cleaner story.
create table if not exists public.audit_events (
  id           uuid primary key default gen_random_uuid(),
  actor_id     uuid references public.users(id) on delete set null,
  action       text not null,
  target_kind  text,
  target_id    uuid,
  metadata     jsonb not null default '{}'::jsonb,
  created_at   timestamptz not null default now()
);

create index if not exists idx_audit_events_created
  on public.audit_events (created_at desc);
create index if not exists idx_audit_events_actor
  on public.audit_events (actor_id, created_at desc);

-- ── RLS toggles ───────────────────────────────────────────────────────────
-- Enable RLS on every table. Policies below are MVP-grade — they grant
-- read access to any authenticated user and write access via app-layer
-- permission helpers. Tighten in a follow-up migration with the full
-- master-plan policy set (see docs/supabase-setup-guide.md §8).
alter table public.users                enable row level security;
alter table public.tasks                enable row level security;
alter table public.submissions          enable row level security;
alter table public.reviews              enable row level security;
alter table public.comments             enable row level security;
alter table public.conversations        enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages             enable row level security;
alter table public.notifications        enable row level security;
alter table public.extension_requests   enable row level security;
alter table public.moderation_reports   enable row level security;
alter table public.audit_events         enable row level security;

-- Helper: app role for the calling user, read from the JWT claim or
-- fallback to the users table. Marked SECURITY DEFINER so policies can
-- call it without recursing through their own RLS.
create or replace function public.current_app_role()
returns app_role
language sql
security definer
set search_path = public
as $$
  select coalesce(
    nullif(auth.jwt() ->> 'app_role', '')::app_role,
    (select role from public.users where id = auth.uid())
  );
$$;

-- ── policies — read ───────────────────────────────────────────────────────
-- Authenticated users can read most tables. Notifications and moderation
-- reports are scoped per-user / per-role.
create policy users_select on public.users
  for select using (auth.role() = 'authenticated');

create policy tasks_select on public.tasks
  for select using (
    auth.role() = 'authenticated'
    and (
      writer_id = auth.uid()
      or editor_id = auth.uid()
      or public.current_app_role() in ('leader','admin')
    )
  );

create policy submissions_select on public.submissions
  for select using (
    exists (
      select 1 from public.tasks t
      where t.id = submissions.task_id
        and (
          t.writer_id = auth.uid()
          or t.editor_id = auth.uid()
          or public.current_app_role() in ('leader','admin')
        )
    )
  );

create policy reviews_select on public.reviews
  for select using (
    exists (
      select 1 from public.submissions s
        join public.tasks t on t.id = s.task_id
      where s.id = reviews.submission_id
        and (
          t.writer_id = auth.uid()
          or t.editor_id = auth.uid()
          or public.current_app_role() in ('leader','admin')
        )
    )
  );

create policy comments_select on public.comments
  for select using (
    exists (
      select 1 from public.submissions s
        join public.tasks t on t.id = s.task_id
      where s.id = comments.submission_id
        and (
          t.writer_id = auth.uid()
          or t.editor_id = auth.uid()
          or public.current_app_role() in ('leader','admin')
        )
    )
  );

create policy conversations_select on public.conversations
  for select using (
    exists (
      select 1 from public.conversation_members m
      where m.conversation_id = conversations.id
        and m.user_id = auth.uid()
    )
    or public.current_app_role() in ('leader','admin') and conversations.kind = 'all_team'
  );

create policy conversation_members_select on public.conversation_members
  for select using (
    user_id = auth.uid()
    or exists (
      select 1 from public.conversation_members m2
      where m2.conversation_id = conversation_members.conversation_id
        and m2.user_id = auth.uid()
    )
  );

create policy messages_select on public.messages
  for select using (
    exists (
      select 1 from public.conversation_members m
      where m.conversation_id = messages.conversation_id
        and m.user_id = auth.uid()
    )
  );

create policy notifications_select on public.notifications
  for select using (user_id = auth.uid());

create policy extension_requests_select on public.extension_requests
  for select using (
    requested_by_id = auth.uid()
    or public.current_app_role() in ('leader','admin')
    or exists (
      select 1 from public.tasks t
      where t.id = extension_requests.task_id
        and (t.editor_id = auth.uid() or t.writer_id = auth.uid())
    )
  );

-- Moderation reports are sensitive — only admins/leaders can see them.
create policy moderation_reports_select on public.moderation_reports
  for select using (
    public.current_app_role() in ('leader','admin')
  );

create policy audit_events_select on public.audit_events
  for select using (
    public.current_app_role() = 'admin'
  );

-- ── policies — write (MVP, broad) ─────────────────────────────────────────
-- These allow any authenticated user to insert/update/delete; the app-layer
-- permission helpers in lib/permissions.ts gate the actual UI. Tighten
-- in a follow-up migration to match the master plan.
create policy users_write on public.users
  for all using (public.current_app_role() = 'admin')
       with check (public.current_app_role() = 'admin');

create policy tasks_write on public.tasks
  for all using (public.current_app_role() in ('leader','admin'))
       with check (public.current_app_role() in ('leader','admin'));

create policy submissions_write on public.submissions
  for all using (
    exists (
      select 1 from public.tasks t
      where t.id = submissions.task_id and t.writer_id = auth.uid()
    )
  ) with check (
    exists (
      select 1 from public.tasks t
      where t.id = submissions.task_id and t.writer_id = auth.uid()
    )
  );

create policy reviews_write on public.reviews
  for all using (
    public.current_app_role() in ('leader','admin')
    or exists (
      select 1 from public.submissions s
        join public.tasks t on t.id = s.task_id
      where s.id = reviews.submission_id and t.editor_id = auth.uid()
    )
  ) with check (
    public.current_app_role() in ('leader','admin')
    or exists (
      select 1 from public.submissions s
        join public.tasks t on t.id = s.task_id
      where s.id = reviews.submission_id and t.editor_id = auth.uid()
    )
  );

create policy comments_write on public.comments
  for all using (auth.role() = 'authenticated')
       with check (author_id = auth.uid());

create policy conversations_write on public.conversations
  for all using (public.current_app_role() in ('leader','admin'))
       with check (public.current_app_role() in ('leader','admin'));

create policy conversation_members_write on public.conversation_members
  for all using (public.current_app_role() in ('leader','admin'))
       with check (public.current_app_role() in ('leader','admin'));

create policy messages_write on public.messages
  for all using (
    author_id = auth.uid()
    or public.current_app_role() in ('leader','admin')
  ) with check (
    author_id = auth.uid()
    or public.current_app_role() in ('leader','admin')
  );

-- Notifications are usually written by edge functions running with the
-- service role; this policy still permits a user to mark their own as read.
create policy notifications_update_own on public.notifications
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy notifications_insert_self on public.notifications
  for insert with check (user_id = auth.uid() or public.current_app_role() = 'admin');

create policy extension_requests_write on public.extension_requests
  for all using (
    requested_by_id = auth.uid()
    or public.current_app_role() in ('leader','admin')
  ) with check (
    requested_by_id = auth.uid()
    or public.current_app_role() in ('leader','admin')
  );

-- Reporters (any authenticated user) can insert reports about a message
-- they can see. Status changes are restricted to leaders/admins.
create policy moderation_reports_insert on public.moderation_reports
  for insert with check (reporter_id = auth.uid());

create policy moderation_reports_update on public.moderation_reports
  for update using (public.current_app_role() in ('leader','admin'))
              with check (public.current_app_role() in ('leader','admin'));

-- Audit events are append-only, written by edge functions. No public writes.
create policy audit_events_insert on public.audit_events
  for insert with check (public.current_app_role() = 'admin');
